mysql:
  host: "localhost"
  port: 3307
  database: "ecommerce_source"
  user: "vijay"
  password: 

snowflake:
  account: "EJTQBXU-PT64687"
  user: "VIJAYPASAM"
  password: 
  warehouse: "WH_ETL_DEV"
  database: "CUSTOMER360_DEV"
  schema_raw: "RAW"

tables:
  - name: "customers"
    source_table: "customers"
    target_table: "raw_customers"
    primary_key: "customer_id"
    incremental_column: "updated_at"
  - name: "products"
    source_table: "products"
    target_table: "raw_products"
    primary_key: "product_id"
    incremental_column: "updated_at"
  - name: "orders"
    source_table: "orders"
    target_table: "raw_orders"
    primary_key: "order_id"
    incremental_column: "updated_at"
  - name: "order_items"
    source_table: "order_items"
    target_table: "raw_order_items"
    primary_key: "order_item_id"
    incremental_column: "updated_at"
